In [113]:
import pandas as pd

In [114]:
df=pd.read_csv("LaptopPrice.csv")

In [115]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [116]:
df.duplicated().sum()

np.int64(21)

In [117]:
df.drop_duplicates(inplace=True)

In [118]:
df.duplicated().sum()

np.int64(0)

In [119]:
df.isnull()

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
819,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
820,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
821,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
822,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [120]:
df.dropna()

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [121]:
df.drop(['os','os_bit','weight','msoffice','rating','Number of Ratings','Number of Reviews'],axis=1,inplace=True)

In [122]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,34649
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,38999
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,39999
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,2 GB,No warranty,No,69990
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,135990
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,144990
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,149990
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,142990
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,0 GB,No warranty,No,57490

In [123]:
df['brand'].unique()

array(['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE'],
      dtype=object)

In [124]:
brand_dict={'ASUS':1, 'Lenovo':2, 'acer':3, 'Avita':4, 'HP':5, 'DELL':6, 'MSI':7, 'APPLE':8}

In [125]:
df['brand']=df['brand'].map(brand_dict)

In [126]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,34649
1,2,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,38999
2,2,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,39999
3,1,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,2 GB,No warranty,No,69990
4,1,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,135990
819,1,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,144990
820,1,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,149990
821,1,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,142990
822,2,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,0 GB,No warranty,No,57490

In [127]:
df['processor_brand'].unique()

array(['Intel', 'AMD', 'M1'], dtype=object)

In [128]:
proc_brand_dict={'Intel':1, 'AMD':2, 'M1':3}

In [129]:
df['processor_brand']=df['processor_brand'].map(proc_brand_dict)

In [130]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,34649
1,2,1,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,38999
2,2,1,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,39999
3,1,1,Core i5,10th,8 GB,DDR4,512 GB,0 GB,2 GB,No warranty,No,69990
4,1,1,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,135990
819,1,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,144990
820,1,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,149990
821,1,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,142990
822,2,2,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,0 GB,No warranty,No,57490

In [131]:
df['processor_name'].unique()

array(['Core i3', 'Core i5', 'Celeron Dual', 'Ryzen 5', 'Core i7',
       'Core i9', 'M1', 'Pentium Quad', 'Ryzen 3', 'Ryzen 7', 'Ryzen 9'],
      dtype=object)

In [132]:
proc_name_dict={'Core i3':1, 'Core i5':2, 'Celeron Dual':3, 'Ryzen 5':4, 'Core i7':5,
       'Core i9':6, 'M1':7, 'Pentium Quad':8, 'Ryzen 3':9, 'Ryzen 7':10, 'Ryzen 9':11}

In [133]:
df['processor_name']=df['processor_name'].map(proc_name_dict)

In [134]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,1,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,34649
1,2,1,1,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,38999
2,2,1,1,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,39999
3,1,1,2,10th,8 GB,DDR4,512 GB,0 GB,2 GB,No warranty,No,69990
4,1,1,3,Not Available,4 GB,DDR4,0 GB,512 GB,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,11,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,135990
819,1,2,11,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,144990
820,1,2,11,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,149990
821,1,2,11,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,142990
822,2,2,4,10th,8 GB,DDR4,512 GB,0 GB,0 GB,No warranty,No,57490

In [135]:
df['processor_gnrtn'].unique()

array(['10th', 'Not Available', '11th', '7th', '8th', '9th', '4th',
       '12th'], dtype=object)

In [136]:
proc_gen_dict={'10th':1, 'Not Available':2, '11th':3, '7th':4, '8th':5, '9th':6, '4th':7,
       '12th':8}

In [137]:
df['processor_gnrtn']=df['processor_gnrtn'].map(proc_gen_dict)

In [138]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,1,1,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,34649
1,2,1,1,1,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,38999
2,2,1,1,1,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,39999
3,1,1,2,1,8 GB,DDR4,512 GB,0 GB,2 GB,No warranty,No,69990
4,1,1,3,2,4 GB,DDR4,0 GB,512 GB,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,11,2,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,135990
819,1,2,11,2,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,144990
820,1,2,11,2,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,149990
821,1,2,11,2,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,142990
822,2,2,4,1,8 GB,DDR4,512 GB,0 GB,0 GB,No warranty,No,57490

In [139]:
df.dtypes

brand               int64
processor_brand     int64
processor_name      int64
processor_gnrtn     int64
ram_gb             object
ram_type           object
ssd                object
hdd                object
graphic_card_gb    object
warranty           object
Touchscreen        object
Price               int64
dtype: object

In [140]:
df['ram_gb'].unique()

array(['4 GB', '8 GB', '16 GB', '32 GB'], dtype=object)

In [141]:
ram_gb_dict={'4 GB':4, '8 GB':8, '16 GB':16, '32 GB':32}

In [142]:
df['ram_gb']=df['ram_gb'].map(ram_gb_dict)

In [143]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,1,1,4,DDR4,0 GB,1024 GB,0 GB,No warranty,No,34649
1,2,1,1,1,4,DDR4,0 GB,1024 GB,0 GB,No warranty,No,38999
2,2,1,1,1,4,DDR4,0 GB,1024 GB,0 GB,No warranty,No,39999
3,1,1,2,1,8,DDR4,512 GB,0 GB,2 GB,No warranty,No,69990
4,1,1,3,2,4,DDR4,0 GB,512 GB,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,11,2,4,DDR4,1024 GB,0 GB,0 GB,1 year,No,135990
819,1,2,11,2,4,DDR4,1024 GB,0 GB,0 GB,1 year,No,144990
820,1,2,11,2,4,DDR4,1024 GB,0 GB,4 GB,1 year,No,149990
821,1,2,11,2,4,DDR4,1024 GB,0 GB,4 GB,1 year,No,142990
822,2,2,4,1,8,DDR4,512 GB,0 GB,0 GB,No warranty,No,57490

In [144]:
df['ram_type'].unique()

array(['DDR4', 'LPDDR4', 'LPDDR4X', 'DDR5', 'DDR3', 'LPDDR3'],
      dtype=object)

In [145]:
ram_type_dict={'DDR4':1, 'LPDDR4':2, 'LPDDR4X':3, 'DDR5':4, 'DDR3':5, 'LPDDR3':6}

In [146]:
df['ram_type']=df['ram_type'].map(ram_type_dict)

In [147]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,1,1,4,1,0 GB,1024 GB,0 GB,No warranty,No,34649
1,2,1,1,1,4,1,0 GB,1024 GB,0 GB,No warranty,No,38999
2,2,1,1,1,4,1,0 GB,1024 GB,0 GB,No warranty,No,39999
3,1,1,2,1,8,1,512 GB,0 GB,2 GB,No warranty,No,69990
4,1,1,3,2,4,1,0 GB,512 GB,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,11,2,4,1,1024 GB,0 GB,0 GB,1 year,No,135990
819,1,2,11,2,4,1,1024 GB,0 GB,0 GB,1 year,No,144990
820,1,2,11,2,4,1,1024 GB,0 GB,4 GB,1 year,No,149990
821,1,2,11,2,4,1,1024 GB,0 GB,4 GB,1 year,No,142990
822,2,2,4,1,8,1,512 GB,0 GB,0 GB,No warranty,No,57490

In [148]:
df['ssd'].unique()

array(['0 GB', '512 GB', '256 GB', '128 GB', '1024 GB', '2048 GB',
       '3072 GB'], dtype=object)

In [149]:
ssd_dict={'0 GB':0, '512 GB':512,'256 GB':256, '128 GB':128, '1024 GB':1024, '2048 GB':2048,
       '3072 GB':3072}

In [150]:
df['ssd']=df['ssd'].map(ssd_dict)

In [151]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,1,1,4,1,0,1024 GB,0 GB,No warranty,No,34649
1,2,1,1,1,4,1,0,1024 GB,0 GB,No warranty,No,38999
2,2,1,1,1,4,1,0,1024 GB,0 GB,No warranty,No,39999
3,1,1,2,1,8,1,512,0 GB,2 GB,No warranty,No,69990
4,1,1,3,2,4,1,0,512 GB,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,11,2,4,1,1024,0 GB,0 GB,1 year,No,135990
819,1,2,11,2,4,1,1024,0 GB,0 GB,1 year,No,144990
820,1,2,11,2,4,1,1024,0 GB,4 GB,1 year,No,149990
821,1,2,11,2,4,1,1024,0 GB,4 GB,1 year,No,142990
822,2,2,4,1,8,1,512,0 GB,0 GB,No warranty,No,57490

In [152]:
df['hdd'].unique()

array(['1024 GB', '0 GB', '512 GB', '2048 GB'], dtype=object)

In [153]:
hdd_dict={'1024 GB':1024, '0 GB':0, '512 GB':512, '2048 GB':2048}

In [154]:
df['hdd']=df['hdd'].map(hdd_dict)

In [155]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,1,1,4,1,0,1024,0 GB,No warranty,No,34649
1,2,1,1,1,4,1,0,1024,0 GB,No warranty,No,38999
2,2,1,1,1,4,1,0,1024,0 GB,No warranty,No,39999
3,1,1,2,1,8,1,512,0,2 GB,No warranty,No,69990
4,1,1,3,2,4,1,0,512,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,11,2,4,1,1024,0,0 GB,1 year,No,135990
819,1,2,11,2,4,1,1024,0,0 GB,1 year,No,144990
820,1,2,11,2,4,1,1024,0,4 GB,1 year,No,149990
821,1,2,11,2,4,1,1024,0,4 GB,1 year,No,142990
822,2,2,4,1,8,1,512,0,0 GB,No warranty,No,57490

In [156]:
df['graphic_card_gb'].unique()

array(['0 GB', '2 GB', '4 GB', '6 GB', '8 GB'], dtype=object)

In [157]:
graphic_card_dict={'0 GB':0, '2 GB':2, '4 GB':4, '6 GB':6, '8 GB':8}

In [158]:
df['graphic_card_gb']=df['graphic_card_gb'].map(graphic_card_dict)

In [159]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,1,1,4,1,0,1024,0,No warranty,No,34649
1,2,1,1,1,4,1,0,1024,0,No warranty,No,38999
2,2,1,1,1,4,1,0,1024,0,No warranty,No,39999
3,1,1,2,1,8,1,512,0,2,No warranty,No,69990
4,1,1,3,2,4,1,0,512,0,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,11,2,4,1,1024,0,0,1 year,No,135990
819,1,2,11,2,4,1,1024,0,0,1 year,No,144990
820,1,2,11,2,4,1,1024,0,4,1 year,No,149990
821,1,2,11,2,4,1,1024,0,4,1 year,No,142990
822,2,2,4,1,8,1,512,0,0,No warranty,No,57490

In [160]:
df['warranty'].unique()

array(['No warranty', '1 year', '2 years', '3 years'], dtype=object)

In [161]:
warranty_dict={'No warranty':1, '1 year':2, '2 years':3, '3 years':4}

In [162]:
df['warranty']=df['warranty'].map(warranty_dict)

In [163]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,1,1,4,1,0,1024,0,1,No,34649
1,2,1,1,1,4,1,0,1024,0,1,No,38999
2,2,1,1,1,4,1,0,1024,0,1,No,39999
3,1,1,2,1,8,1,512,0,2,1,No,69990
4,1,1,3,2,4,1,0,512,0,1,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,11,2,4,1,1024,0,0,2,No,135990
819,1,2,11,2,4,1,1024,0,0,2,No,144990
820,1,2,11,2,4,1,1024,0,4,2,No,149990
821,1,2,11,2,4,1,1024,0,4,2,No,142990
822,2,2,4,1,8,1,512,0,0,1,No,57490

In [164]:
df['Touchscreen'].unique()

array(['No', 'Yes'], dtype=object)

In [165]:
touchscreen_dict={'No':1, 'Yes':2}

In [166]:
df['Touchscreen']=df['Touchscreen'].map(touchscreen_dict)

In [167]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,1,1,4,1,0,1024,0,1,1,34649
1,2,1,1,1,4,1,0,1024,0,1,1,38999
2,2,1,1,1,4,1,0,1024,0,1,1,39999
3,1,1,2,1,8,1,512,0,2,1,1,69990
4,1,1,3,2,4,1,0,512,0,1,1,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,11,2,4,1,1024,0,0,2,1,135990
819,1,2,11,2,4,1,1024,0,0,2,1,144990
820,1,2,11,2,4,1,1024,0,4,2,1,149990
821,1,2,11,2,4,1,1024,0,4,2,1,142990
822,2,2,4,1,8,1,512,0,0,1,1,57490

In [170]:
df.to_csv('clean_lptp.csv')

In [171]:
x=df.drop('Price',axis=1)
y=df[['Price']]

In [172]:
x

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen
0,1,1,1,1,4,1,0,1024,0,1,1
1,2,1,1,1,4,1,0,1024,0,1,1
2,2,1,1,1,4,1,0,1024,0,1,1
3,1,1,2,1,8,1,512,0,2,1,1
4,1,1,3,2,4,1,0,512,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,11,2,4,1,1024,0,0,2,1
819,1,2,11,2,4,1,1024,0,0,2,1
820,1,2,11,2,4,1,1024,0,4,2,1
821,1,2,11,2,4,1,1024,0,4,2,1
822,2,2,4,1,8,1,512,0,0,1,1

In [173]:
y

      Price
0     34649
1     38999
2     39999
3     69990
4     26990
..      ...
818  135990
819  144990
820  149990
821  142990
822   57490

[802 rows x 1 columns]

In [174]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42, test_size=0.2)

In [175]:
x_train

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen
442,1,1,2,3,8,1,256,1024,0,2,1
598,1,1,5,1,16,3,0,512,6,1,1
452,1,1,2,3,8,1,256,1024,2,2,1
696,6,2,4,2,8,1,512,0,0,2,1
339,1,1,2,3,8,3,512,0,0,2,2
...,...,...,...,...,...,...,...,...,...,...,...
73,2,1,1,1,4,1,256,0,0,1,1
108,6,1,1,3,8,1,512,0,0,2,2
275,2,1,2,1,8,1,512,0,2,2,1
445,1,1,2,3,8,1,256,1024,0,2,1
104,1,1,1,3,8,1,512,0,0,2,1

In [176]:
x_test

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen
196,3,1,2,2,8,4,0,512,4,1,1
299,1,1,2,3,8,3,512,0,0,2,1
171,6,1,1,1,8,1,256,1024,0,2,1
537,5,1,5,1,16,1,1024,0,6,2,1
551,7,1,5,3,16,1,1024,0,8,3,1
...,...,...,...,...,...,...,...,...,...,...,...
368,1,1,2,3,8,3,512,0,0,2,2
361,5,1,2,1,8,1,512,0,0,2,2
446,6,1,2,3,8,1,256,1024,0,2,1
767,2,2,10,2,4,1,512,0,4,2,1
529,2,1,5,3,16,1,512,0,0,1,1

In [177]:
y_train

      Price
442   50990
598  146490
452   60190
696   59490
339   99990
..      ...
73    41990
108   60790
275   57500
445   52990
104   44990

[641 rows x 1 columns]

In [178]:
y_test

      Price
196   50990
299   72990
171   41490
537  144690
551  129990
..      ...
368  114990
361  126000
446   57990
767  106990
529  110999

[161 rows x 1 columns]

In [179]:
x_test.shape,y_test.shape,x_train.shape,y_train.shape

((161, 11), (161, 1), (641, 11), (641, 1))

In [180]:
from sklearn.linear_model import LinearRegression

In [181]:
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [182]:
lr.score(x_test,y_test)

0.5126275942844929

In [183]:
pred=lr.predict(x_test)

In [184]:
pred

array([[ 83644.0261531 ],
       [ 73548.12274394],
       [ 64293.63389928],
       [153554.87865022],
       [166395.54454022],
       [151272.1471979 ],
       [ 88358.42610495],
       [ 95575.54766501],
       [ 55432.41089828],
       [ 83154.73545359],
       [ 25034.14738201],
       [ 46548.40633215],
       [ 75577.81015065],
       [ 92345.0537206 ],
       [ 64286.94570361],
       [ 82854.41158117],
       [ 84287.39071307],
       [ 63985.95821769],
       [ 63093.22403857],
       [162379.54238514],
       [ 36132.47773946],
       [ 27957.56940781],
       [ 75358.43789849],
       [ 47979.24110685],
       [ 35618.38254811],
       [ 39456.21376262],
       [ 78696.59549018],
       [158756.63464953],
       [ 38563.47958351],
       [ 26897.74578964],
       [ 57810.10449726],
       [ 53775.23200041],
       [ 62820.97126157],
       [ 57317.91255552],
       [ 55216.57972919],
       [ 25034.14738201],
       [123290.99929388],
       [ 66431.38163026],
       [ 51921.23970951],
       [ 93511.24217744],
       [ 28163.98891758],
       [ 97227.38279666],
       [ 71708.6640272 ],
       [ 36036.69262895],
       [ 77457.13702983],
       [ 38172.54381358],
       [138746.32527292],
       [ 60559.74888835],
       [110499.32714354],
       [111451.78771639],
       [130292.50294032],
       [ 93646.96280339],
       [ 68334.6635437 ],
       [ 86263.26805668],
       [ 73885.77526079],
       [162017.40303   ],
       [110292.90763377],
       [ 60649.69717235],
       [ 73472.93624125],
       [133696.29512061],
       [ 89525.3631024 ],
       [ 41023.56319806],
       [ 43766.67710441],
       [ 76832.99708255],
       [ 93293.76647163],
       [ 75566.75395461],
       [155602.99331801],
       [ 37592.61535499],
       [ 43766.67710441],
       [ 53753.7256726 ],
       [133886.6578665 ],
       [157426.5746126 ],
       [ 69991.84244156],
       [ 92345.0537206 ],
       [ 37592.61535499],
       [ 35729.01694736],
       [110161.00425519],
       [ 91400.01770607],
       [ 55432.41089828],
       [ 57080.17813682],
       [ 36308.94540595],
       [ 49663.70648731],
       [ 79210.69068153],
       [ 25034.14738201],
       [ 35618.38254811],
       [ 64561.94607826],
       [ 84978.40866671],
       [106357.09160137],
       [ 55638.83040805],
       [151272.1471979 ],
       [ 77430.35236224],
       [ 57111.49304575],
       [ 91117.22303328],
       [ 80271.38855799],
       [ 65777.03516242],
       [102341.08944628],
       [144801.12557423],
       [ 75577.81015065],
       [ 38941.55043937],
       [ 61436.04514071],
       [ 74915.98200173],
       [ 39271.69750247],
       [118575.91537339],
       [ 64254.27039668],
       [ 76678.32423754],
       [ 89525.3631024 ],
       [ 64583.31349739],
       [ 82854.41158117],
       [ 28370.40842735],
       [ 88110.14674863],
       [ 80662.32432792],
       [ 93628.72366965],
       [ 61229.62563094],
       [ 73885.77526079],
       [ 53390.90330257],
       [ 63400.89972016],
       [ 54667.96617953],
       [ 64354.99058118],
       [ 66429.48508391],
       [ 53195.30354183],
       [149592.15974821],
       [ 68375.68996944],
       [ 55432.41089828],
       [ 79819.10215727],
       [ 58836.11541423],
       [ 56832.55207308],
       [ 43766.67710441],
       [ 71915.08353697],
       [163361.47772162],
       [ 60752.51086723],
       [ 61229.62563094],
       [ 52302.56936271],
       [112985.1201505 ],
       [203332.65517852],
       [ 35935.43645713],
       [ 74399.87045214],
       [143009.56382172],
       [115390.71437575],
       [ 77008.10168339],
       [ 76091.905342  ],
       [178820.78782201],
       [ 59313.29381489],
       [ 76832.99708255],
       [ 46749.56109927],
       [ 63299.64354834],
       [157046.55337874],
       [ 49088.25445722],
       [ 65233.86648364],
       [ 72628.0022388 ],
       [ 89277.76431655],
       [ 61229.62563094],
       [ 92345.0537206 ],
       [ 55247.89463812],
       [ 28678.08410894],
       [ 70881.10950488],
       [148934.94765584],
       [ 91117.22303328],
       [ 80271.38855799],
       [ 63400.89972016],
       [ 80281.25292514],
       [ 79387.61344381]])